from enum import Enum

class ADV_OBJ_TYPE(Enum):
    ADV_DEVICE = 0
    ADV_AXIS = 1
    ADV_GROUP = 2
    ADV_LATCH_CHANNEL = 3
    ADV_COMPARE_CHANNEL = 4
    ADV_RING = 5
    ADV_GENERAL_DI_PORT = 6
    ADV_GENERAL_DO_PORT = 7
    ADV_GENERAL_AI_CHANNEL = 8
    ADV_GENERAL_AO_CHANNEL = 9
    ADV_COUNTER_CHANNEL = 10
    ADV_MDAQ_CHANNEL = 11
    ADV_EXT_DRIVE_CHANNEL = 12

class DO_ONOFF(Enum):
    DO_OFF = 0
    DO_ON = 1

class ECAT_ID_TYPE(Enum):
    SUBDEVICE_ID = 0
    SUBDEVICE_POS = 1

class ABS_MODE(Enum):
    MOVE_REL = 0
    MOVE_ABS = 1

class MOTION_DIRECTION(Enum):
    DIRECTION_POS = 0
    DIRECTION_NEG = 1

class HOME_MODE(Enum):
    MODE1_ABS = 0
    MODE2_LMT = 1
    MODE3_REF = 2
    MODE4_ABS_REF = 3
    MODE5_ABS_NEG_REF = 4
    MODE6_LMT_REF = 5
    MODE7_ABS_SEARCH = 6
    MODE8_LMT_SEARCH = 7
    MODE9_ABS_SEARCH_REF = 8
    MODE10_ABS_SEARCH_NEG_REF = 9
    MODE11_LMT_SEARCH_REF = 10
    MODE12_ABS_SEARCH_REFIND = 11
    MODE13_LMT_SEARCH_REFIND = 12
    MODE14_ABS_SEARCH_REFIND_REF = 13
    MODE15_ABS_SEARCH_REFIND_NEG_REF = 14
    MODE16_LMT_SEARCH_REFIND_NEG_REF = 15

class AXIS_STATUS_TYPE(Enum):
    AXIS_STATE = 0
    MOTION_STATUS = 1

class POSITION_TYPE(Enum):
    POSITION_CMD = 0
    POSITION_ACT = 1

class VELOCITY_TYPE(Enum):
    VELOCITY_CMD = 0
    VELOCITY_ACT = 1

class GP_LINE_MODE(Enum):
    LINE_REL = 0
    LINE_ABS = 1
    DIRECT_REL = 2
    DIRECT_ABS = 3

class ARC_DIRECTION(Enum):
    ARC_CW = 0
    ARC_CCW = 1

class PATH_MOVE_MODE_CM2(Enum):
    BUFFER_MODE = 0
    BLENDING_MODE = 1
    FLY_MODE = 2
    SPEED_FORWARD_MODE = 3

class MOTION_STOP_MODE(Enum):
    MOTION_STOP_MODE_DEC = 0
    MOTION_STOP_MODE_EMG = 1

class EXT_DRIVE_MODE(Enum):
    JOG_STOP_MODE = 0
    JOG_MODE = 1
    MPG_MODE = 2

class ADV_EVENT_SUBSCRIBE(Enum):
    EVENT_DISABLE = -1
    AXIS_MOTION_DONE = 0
    AXIS_COMPARE = 1
    AXIS_LATCHED = 2
    AXIS_ERROR = 3
    AXIS_VH_START = 4
    AXIS_VH_END = 5
    AXIS_LATCH_BUFFER_DONE = 6
    AXIS_GEAR_IN = 7
    GROUP_MOTION_DONE = 100
    GROUP_VH_START = 101
    GROUP_VH_END = 102
    DEVICE_LATCHED = 200
    DEVICE_DISCONNECT = 300
    DEVICE_IO_DISCONNECT = 301
    DEVICE_MODE_CHANGE = 302
    DEVICE_IO_MODE_CHANGE = 303
    DEVICE_LOST_FRAME = 304
    DEVICE_IO_LOST_FRAME = 305
    DEVICE_LOST_FRAME_WARN = 306
    DEVICE_IO_LOST_FRAME_WARN = 307
    DEVICE_COMM_RECOVERY = 308
    DEVICE_IO_COMM_RECOVERY = 309